"""autogenerated by genpy from idSLAM/Edge.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Edge(genpy.Message):
  _md5sum = "550e51b7310e6434fc075f844fbb398f"
  _type = "idSLAM/Edge"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 idA # keyframe A's id
int64 idB # keyframe B's id, idA < idB

geometry_msgs/Pose poseATB

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['idA','idB','poseATB']
  _slot_types = ['int64','int64','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       idA,idB,poseATB

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Edge, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.idA is None:
        self.idA = 0
      if self.idB is None:
        self.idB = 0
      if self.poseATB is None:
        self.poseATB = geometry_msgs.msg.Pose()
    else:
      self.idA = 0
      self.idB = 0
      self.poseATB = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2q7d.pack(_x.idA, _x.idB, _x.poseATB.position.x, _x.poseATB.position.y, _x.poseATB.position.z, _x.poseATB.orientation.x, _x.poseATB.orientation.y, _x.poseATB.orientation.z, _x.poseATB.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.poseATB is None:
        self.poseATB = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.idA, _x.idB, _x.poseATB.position.x, _x.poseATB.position.y, _x.poseATB.position.z, _x.poseATB.orientation.x, _x.poseATB.orientation.y, _x.poseATB.orientation.z, _x.poseATB.orientation.w,) = _struct_2q7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2q7d.pack(_x.idA, _x.idB, _x.poseATB.position.x, _x.poseATB.position.y, _x.poseATB.position.z, _x.poseATB.orientation.x, _x.poseATB.orientation.y, _x.poseATB.orientation.z, _x.poseATB.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.poseATB is None:
        self.poseATB = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.idA, _x.idB, _x.poseATB.position.x, _x.poseATB.position.y, _x.poseATB.position.z, _x.poseATB.orientation.x, _x.poseATB.orientation.y, _x.poseATB.orientation.z, _x.poseATB.orientation.w,) = _struct_2q7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2q7d = struct.Struct("<2q7d")
