"""autogenerated by genpy from idSLAM/Mappoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Mappoint(genpy.Message):
  _md5sum = "681354f53636712a7f05b245acd6b162"
  _type = "idSLAM/Mappoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 px # x coordinate of its 3d position relative to kf
float32 py
float32 pz

int32 level # in which pyramid level of the kf was it found?

float32 ix # x coordinate of its 2D pixel position in the KF (not level)
float32 iy
float32 depth # measured depth in [m] or 0 if not available

"""
  __slots__ = ['px','py','pz','level','ix','iy','depth']
  _slot_types = ['float32','float32','float32','int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       px,py,pz,level,ix,iy,depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Mappoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.px is None:
        self.px = 0.
      if self.py is None:
        self.py = 0.
      if self.pz is None:
        self.pz = 0.
      if self.level is None:
        self.level = 0
      if self.ix is None:
        self.ix = 0.
      if self.iy is None:
        self.iy = 0.
      if self.depth is None:
        self.depth = 0.
    else:
      self.px = 0.
      self.py = 0.
      self.pz = 0.
      self.level = 0
      self.ix = 0.
      self.iy = 0.
      self.depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3fi3f.pack(_x.px, _x.py, _x.pz, _x.level, _x.ix, _x.iy, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.px, _x.py, _x.pz, _x.level, _x.ix, _x.iy, _x.depth,) = _struct_3fi3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3fi3f.pack(_x.px, _x.py, _x.pz, _x.level, _x.ix, _x.iy, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.px, _x.py, _x.pz, _x.level, _x.ix, _x.iy, _x.depth,) = _struct_3fi3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3fi3f = struct.Struct("<3fi3f")
